# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('picurl', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=20)),
                ('tag', models.CharField(max_length=20)),
                ('score', models.IntegerField(default=0)),
                ('qrytime', models.IntegerField(default=0)),
                ('parentid', models.IntegerField(default=0)),
                ('childsize', models.IntegerField(default=0)),
            ],
        ),
    ]
