# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dytt', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
