# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dytt', '0002_auto_20170805_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='failvideo',
            name='childsize',
            field=models.IntegerField(default=0),
        ),
    ]
