# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 03:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dytt', '0002_auto_20170731_0348'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set([('name', 'url')]),
        ),
    ]
