# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dytt', '0003_failvideo_childsize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=180),
        ),
    ]
