# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dytt', '0003_auto_20170731_0350'),
    ]

    operations = [
        migrations.CreateModel(
            name='FailVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'failvideo',
            },
        ),
        migrations.AlterUniqueTogether(
            name='failvideo',
            unique_together=set([('url', 'type')]),
        ),
    ]
