# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('tokenid', models.CharField(max_length=100)),
                ('sex', models.IntegerField(default=2)),
                ('country', models.CharField(max_length=20)),
                ('isfollow', models.BooleanField(default=False)),
                ('lastlogintime', models.DateField(auto_now=True)),
                ('createtime', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'wechatuser',
            },
        ),
    ]
